[theme]
primaryColor = "#194485"  # El azul cl√°sico de Bootstrap (Primary)
backgroundColor = "#1e2f41" # Gris muy claro de fondo (tipo Bootstrap)
secondaryBackgroundColor = "#000000" # Blanco para el sidebar y tarjetas
textColor = "#ffffff" # Gris oscuro para texto
font = "comic sans"

[server]
runOnSave = true

[client]
showSidebarNavigation = false